### PR TITLE
Fix the issue where access entries don't expire. Upgrade the project to .net 10

### LINKED ISSUE #71: Implement Access Expiry
> tried deny with 5 min timer but timer wasn't removed after 5mins
> 
> //access # add deny (asterisk)!(asterisk)@(asterisk) 5 :lol 

 _Originally posted by @alkaholix in [#67](https://github.com/irc7-com/irc7/issues/67#issuecomment-2826464190)_

### PR DESCRIPTION
**Pull request by joachimjusth**
should fix #71

### CODE REVIEW

File: Irc/Objects/AccessList.cs [hunk 1]
```diff
@@ -28,6 +38,7 @@ public EnumAccessError Clear(EnumUserAccessLevel userAccessLevel, EnumAccessLeve
 
     public EnumAccessError Add(AccessEntry accessEntry)
     {
+        PruneExpired();
```
Comment (jyonxo) [inline Irc/Objects/AccessList.cs]: I dont think we need to worry about pruning here so we can save cycles and not do it

File: Irc/Objects/AccessList.cs [hunk 2]
```diff
@@ -40,6 +51,7 @@ public EnumAccessError Add(AccessEntry accessEntry)
 
     public EnumAccessError Delete(AccessEntry accessEntry)
     {
+        PruneExpired();
```
Comment (jyonxo) [inline Irc/Objects/AccessList.cs]: I dont think we need to worry about pruning here so we can save cycles and not do it
